version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: kaan-koh-gym-api_nginx
    ports:
        - 80:80
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - ./:/var/www/html/
    environment:
      - NGINX_HOST=kaan-koh-gym.test
      - NGINX_PORT=80    
    links:
        - wordpress
    restart: "no"
  
  wordpress:
    build:
      context: ./wordpress-fpm/
      dockerfile: ./Dockerfile
    depends_on:
      - db
    container_name: kaan-koh-gym-api_wordpress
    restart: "no"
    ports:
      - 9000:9000
    working_dir: /var/www/html
    restart: on-failure:5
    volumes:        
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/themes:/var/www/html/wp-content/themes
      # - ./wordpress:/var/www/html/
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:     
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: kaan-koh-gym-db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Sawaddee0621
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      XDEBUG_CONFIG: remote_host=192.168.1.2
      
  # here is our mailhog container
  mailhog:
    image: mailhog/mailhog:latest
    container_name: kaan-koh-gym-api_mailhog
    ports:
      - "8025:8025"
      
  db:
    image: mariadb:10.5.8-focal
    container_name: kaan-koh-gym-api_mysql
    restart: "no"
    ports:
      - 3306:3306
    volumes:
      # - ./wordpress.sql:/docker-entrypoint-initdb.d/init.sql # prepopulate database
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: kaan-koh-gym-db
      MYSQL_ROOT_PASSWORD: Sawaddee0621
      MYSQL_USER: root
      MYSQL_PASSWORD: Sawaddee0621    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kaan-koh-gym-api_phpmyadmin
    environment:
      - PMA_HOST=kaan-koh-gym-api_mysql
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=Sawaddee0621
    restart: "no"
    ports:
      - 8090:80
    volumes:
      - /sessions
    depends_on:
      - db

volumes:
  mysql:
  mailhog:
  wordpress: